### ISSUE TITLE
Build NETCONF request from JSON/YAML/dict

### ISSUE THREAD

**Issue by wisotzky** [CESNET/libyang-python#25]
I've got following use-case...

Data-structure provided:
```
changes:
  - path: '/vendor:configure/services'
    operation: remove
  - path: '/vendor:configure/system'
    operation: replace
    data:
      name: pe1
      location: Zurich
```

I am searching for a way to translate this structure into a valid NETCONF (rfc6241) compliant change request. The challenge is, that with libyang-python today, I can not add XML attributes (nc:operation value in this case).

Not sure, if this could be done with libyang... I've found however in libyang2 specific methods that provide this sort of access.
